export enum SignUpStep {
  CONFIRM_SIGN_UP = "CONFIRM_SIGN_UP",
  DONE = "DONE",
  COMPLETE_AUTO_SIGN_IN = "COMPLETE_AUTO_SIGN_IN",
}

export enum SignInStep {
  CONFIRM_SIGN_IN_WITH_NEW_PASSWORD_REQUIRED = "CONFIRM_SIGN_IN_WITH_NEW_PASSWORD_REQUIRED",
  CONFIRM_SIGN_IN_WITH_CUSTOM_CHALLENGE = "CONFIRM_SIGN_IN_WITH_CUSTOM_CHALLENGE",
  CONFIRM_SIGN_IN_WITH_TOTP_CODE = "CONFIRM_SIGN_IN_WITH_TOTP_CODE",
  CONFIRM_SIGN_IN_WITH_SMS_CODE = "CONFIRM_SIGN_IN_WITH_SMS_CODE",
  CONFIRM_SIGN_IN_WITH_EMAIL_CODE = "CONFIRM_SIGN_IN_WITH_EMAIL_CODE",
  CONFIRM_SIGN_IN_WITH_PASSWORD = "CONFIRM_SIGN_IN_WITH_PASSWORD",
  CONTINUE_SIGN_IN_WITH_FIRST_FACTOR_SELECTION = "CONTINUE_SIGN_IN_WITH_FIRST_FACTOR_SELECTION",
  CONTINUE_SIGN_IN_WITH_MFA_SELECTION = "CONTINUE_SIGN_IN_WITH_MFA_SELECTION",
  CONTINUE_SIGN_IN_WITH_MFA_SETUP_SELECTION = "CONTINUE_SIGN_IN_WITH_MFA_SETUP_SELECTION",
  CONTINUE_SIGN_IN_WITH_TOTP_SETUP = "CONTINUE_SIGN_IN_WITH_TOTP_SETUP",
  CONTINUE_SIGN_IN_WITH_EMAIL_SETUP = "CONTINUE_SIGN_IN_WITH_EMAIL_SETUP",
  RESET_PASSWORD = "RESET_PASSWORD",
  CONFIRM_SIGN_UP = "CONFIRM_SIGN_UP",
  DONE = "DONE",
}
